### ISSUE TITLE
问题

### ISSUE THREAD

**Issue by lytkx111** [leoli0131/SwinOpenGait#1]
Traceback (most recent call last):
  File "opengait/main.py", line 73, in <module>
    run_model(cfgs, training)
  File "opengait/main.py", line 54, in run_model
    Model.run_train(model)
  File "D:\SwinOpenGait-main\SwinOpenGait-main\opengait\modeling\base_model.py", line 420, in run_train
    retval = model(ipts)
  File "D:\anaconda\envs\OpenGait\lib\site-packages\torch\nn\modules\module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\anaconda\envs\OpenGait\lib\site-packages\torch\nn\parallel\distributed.py", line 886, in forward
    output = self.module(*inputs[0], **kwargs[0])
  File "D:\anaconda\envs\OpenGait\lib\site-packages\torch\nn\modules\module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\SwinOpenGait-main\SwinOpenGait-main\opengait\modeling\models\baseline.py", line 25, in forward
    outs = self.Backbone(sils)  # [n, c, s, h, w]
  File "D:\anaconda\envs\OpenGait\lib\site-packages\torch\nn\modules\module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\SwinOpenGait-main\SwinOpenGait-main\opengait\modeling\modules.py", line 47, in forward
    1, 2).reshape(-1, c, h, w), *args, **kwargs)
  File "D:\anaconda\envs\OpenGait\lib\site-packages\torch\nn\modules\module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\SwinOpenGait-main\SwinOpenGait-main\opengait\modeling\backbones\swinv2.py", line 625, in forward
    x = self.forward_features(x)
  File "D:\SwinOpenGait-main\SwinOpenGait-main\opengait\modeling\backbones\swinv2.py", line 610, in forward_features
    x = self.patch_embed(x)
  File "D:\anaconda\envs\OpenGait\lib\site-packages\torch\nn\modules\module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\SwinOpenGait-main\SwinOpenGait-main\opengait\modeling\backbones\swinv2.py", line 489, in forward
    f"Input image size ({H}*{W}) doesn't match model ({self.img_size[0]}*{self.img_size[1]})."
AssertionError: Input image size (64*64) doesn't match model (224*224).
我model cfg中的type设置为 type:  SwinTransformerV2，我使用的是casia-b数据集但却发生了数据集图片大小不匹配的问题，我看报错是因为需要数据集图片大小为224*224大小的数据集请问是我哪里设置出错了吗？

**Comment by lytkx111** [comment]
而且如果我用vit的backbone训练精度很低60000轮NM精度只有60%
